### ISSUE TITLE
Why does the Connector handle "connection" event with a single-call handler?

### ISSUE THREAD

**Issue by tSte** [GoogleCloudPlatform/cloud-sql-nodejs-connector#349] opened 2024-05-15 08:41 UTC
## Question

The Connector provides capability to connect via UNIX sockets. I'd like to ask if there is a reason why Connector uses `.once()` instead of `.on()` when handling [new connections](https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/f71ee94080f6b42a2cf7b5dcac23a5d5666acd18/src/connector.ts#L308). Is this a bug or by design? If it is by design, why? What will happen in case of ORM connects with multiple connections in connection pool (for example setting [Prisma `connection_limit` greater than `1`](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool#setting-the-connection-pool-size))?

**Comment by jackwotherspoon** [comment] 2024-05-17 20:37
Probably just an oversight.

> What will happen in case of ORM connects with multiple connections in connection pool (for example setting [Prisma connection_limit greater than 1](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool#setting-the-connection-pool-size))?

Were you able to give this a try? If so I'd be curious about the results and if it broke.

**Comment by tSte** [comment] 2024-05-20 08:19
@jackwotherspoon I did not do so with the Connector - we have our internal UNIX socket implementation for two reasons:
1. Historical - we were using this before it was an option with the Connector.
2. Logging - the Connector does not really provide any ability to handle errors and/or closing events of sockets and does not seem to gracefully close connections.

Correct me if I'm wrong, but it does not `.unpipe()` or `.end()` sockets, rather just plainly calls `.destroy()` on TLS Socket. Also it does not seem to `.end()` UNIX socket stream, but only `.close()` UNIX socket. So while it will stop the server to accept new connection, it does not gracefully clean up existing connections. I have a suspicion that non-graceful termination will emit ` FATAL:  connection to client lost` by Cloud SQL in GCP logging with severity of `ALERT` - we have alerting policy on this one, waking up on-call engineers during night.

To answer your question though, our implementation does use `.on('connection', ...)` event handling and we have 2 connections in connection pool, so we often see multiple `connection` events in our logs.

**Comment by jackwotherspoon** [comment] 2024-05-22 20:42
@tSte I will be looking into this this week and will provide an update soon

**Comment by rstreefland** [comment] 2024-06-13 08:26
@jackwotherspoon I can confirm that setting the prisma `connection_limit` greater than 1 consistently results in a timeout whenever prisma tries to establish more than one connection. With the `connection_limit` set to 1, I don't see this error at all. This one is also a blocker for us unfortunately because a single connection is insufficient.

![Screenshot 2024-06-12 at 17 14 23](https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/assets/972022/67180408-7792-4c5a-8a52-2dc32612eaca)

**Comment by jackwotherspoon** [comment] 2024-06-13 13:29
@rstreefland Thanks for the extra details! Currently working on the fix for this and hoping to have it wrapped up shortly, will cut a release when the fix is complete.

**Comment by rstreefland** [comment] 2024-06-13 14:03
@jackwotherspoon Great! Thanks again.

**Closed** 2024-06-21 18:49 UTC
Labels: type: bug, priority: p2

**Comment by jackwotherspoon** [comment] 2024-06-21 20:15
@rstreefland I have a cut a release (v1.3.2) with the change: https://www.npmjs.com/package/@google-cloud/cloud-sql-connector

**Comment by tSte** [comment] 2024-06-25 12:34
@jackwotherspoon IIUC, the `.end()` will send the `FIN` packet (graceful connection termination) so I'd go for handling connections in following "fashion" (I'll just write some code out of my head, did not test this!):
```ts
const disposeSockets = (proxySocket: Socket, connectorSocket: TLSSocket) => {
  // Unpipe streams first
  connectorSocket.unpipe(proxySocket)
  proxySocket.unpipe(connectorSocket)

  // Gracefully close connections
  [proxySocket, connectorSocket].forEach((s) => {
    s.end(() => s.destroy())
  })
}
```

and then something like
```ts
const openSockets = new Set()
unixProxy.on('connection', (proxySocket) => {
  const connectorSocket = stream() // from Connector.getOptions()
  [proxySocket, connectorSocket].forEach((socket) => {
    socket.once('close', (hadError) => {
      // Maybe you'd like to handle hadError = true in some way?
      disposeSockets(proxySocket, connectorSocket)
    })
    socket.once('error', () => {
      disposeSockets(proxySocket, connectorSocket)
    })
  })

  proxySocket.pipe(connectorSocket)
  connectorSocket.pipe(proxySocket)

  openSockets.add({ proxySocket, connectorSocket })
})

unixProxy.once('error', () => {
  // depending on error, but in general
  openSockets.forEach(({ proxySocket, connectorSocket }) => disposeSockets( proxySocket, connectorSocket))
  unixPoroxy.close()
  unlink(socketPath)
})

unixProxy.once('close', () => sqlConnector.close())
```
