### ISSUE TITLE
Module '"node:tls"' has no default export

### ISSUE THREAD

**Issue by Zwiqler94** [GoogleCloudPlatform/cloud-sql-nodejs-connector#197] opened 2023-09-10 19:00 UTC
## Bug Description

Trying to build a firebase function that uses the connector for node and the package has an issue with importing tls.

```log
node_modules/@google-cloud/cloud-sql-connector/dist/cjs/connector.d.ts:2:8 - error TS1192: Module '"node:tls"' has no default export.

2 import tls from 'node:tls';
         ~~~

Found 1 error in node_modules/@google-cloud/cloud-sql-connector/dist/cjs/connector.d.ts:2
```

## Example code (or command)

```typescript
import { Router, Request, Response } from 'express';
import { Pool, ClientConfig, QueryResult } from 'pg';
import { error, info } from 'firebase-functions/logger';
import { Connector, IpAddressTypes } from '@google-cloud/cloud-sql-connector';

const connector = new Connector();
// let clientOpts: any;
const clientOpts = await connector.getOptions({
  instanceConnectionName: (process.env.NODE_ENV === 'prod'
    ? process.env.DB_HOST_PROD
    : process.env.DB_HOST_DEV) as string,
  ipType: IpAddressTypes.PUBLIC,
});

export const postRouter = Router();

const dbConfig: ClientConfig = {
  database: process.env.DB_NAME,
  user: process.env.DB_USER,
  password:
    process.env.NODE_ENV === 'prod'
      ? process.env.DB_PASS_PROD
      : process.env.DB_PASS_DEV,
  ...clientOpts,
};

const pool: Pool = new Pool(dbConfig);
```

## How to reproduce

  1. run the code with a firebase function gen2  using express

#### Environment details

  - OS: MacOS 14
  - Node.js version: 18.17
  - npm version: 10.1

**Comment by ruyadorno** [comment] 2023-09-11 17:43
hi @Zwiqler94 thanks for reporting the issue and providing example code 😊 I'm going to take a look at it.

**Comment by jackwotherspoon** [comment] 2023-09-14 18:55
@Zwiqler94  I'll aim to try and re-produce this error shortly. In the meantime I found a related [SO post](https://stackoverflow.com/questions/40429927/error-ts1192-module-a-module-has-no-default-export) that may help provide a workaround in the near future. Let me know if any of the responses solve the issue for you.

**Comment by Zwiqler94** [comment] 2023-09-14 19:17
Appreciate it! I'll try it out when I can.

**Comment by edosrecki** [comment] 2023-09-14 19:25
@Zwiqler94 Could you share your`tsconfig.json` and what command do you use to run this code?

**Comment by Zwiqler94** [comment] 2023-09-15 04:40
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "resolveJsonModule": true
  },
  "compileOnSave": true,
  "include": ["src"]
}

```

I used `tsc` to compile it

**Comment by edosrecki** [comment] 2023-09-15 06:56
@Zwiqler94 Thanks.

Here is a fix for you:

```diff
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "resolveJsonModule": true,
+   "esModuleInterop": true
  },
  "compileOnSave": true,
  "include": ["src"]
}
```

**Comment by ruyadorno** [comment] 2023-09-18 20:59
hi @Zwiqler94 did @edosrecki's suggestion fixed it for you?

**Comment by Zwiqler94** [comment] 2023-09-20 03:47
> hi @Zwiqler94 did @edosrecki's suggestion fixed it for you?

Apologies, I was confused. Thanks, this solves the import error, but doesn't help with my code sample above or the examples from the readme for other reasons like top-level awaits.

**Comment by Zwiqler94** [comment] 2023-09-20 23:43
> > hi @Zwiqler94 did @edosrecki's suggestion fixed it for you?
> 
> Apologies, I was confused. Thanks, this solves the import error, but doesn't help with my code sample above or the examples from the readme for other reasons like top-level awaits.

This is the only tsconfig that works for the sample code above:

```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es2017",
    "esModuleInterop": true,
    "skipLibCheck": true,
    
    "allowJs": true,
    "moduleDetection": "force",

    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
  },

  "compileOnSave": true,
  "include": ["src"]
}
```

**Comment by edosrecki** [comment] 2023-09-21 09:40
@Zwiqler94 

1. Add `"type": "module"` to `package.json`
2. Add `"moduleResolution": "node"` to your `tsconfig.json`
3. Change `import { Pool, ClientConfig, QueryResult } from 'pg'` to `import pg from 'pg'`, `Pool` to `pg.Pool`, etc.
4. Run with `ts-node --esm index.ts`

Let me know if that works.

**Comment by ruyadorno** [comment] 2023-09-21 18:59
I can confirm that the suggestions from @edosrecki works as expected, I ended up with a slightly tweaked, here is how it looks like in the end:

<table><tbody>
  <tr><td><strong>package.json</strong></td></tr>
  <tr><td>
  
```json
{
  "name": "test-connector-express",
  "version": "1.0.0",
  "main": "index.js",
  "type": "module",
  "dependencies": {
    "@google-cloud/cloud-sql-connector": "^0.5.1",
    "@types/pg": "^8.10.2",
    "pg": "^8.11.3",
    "ts-node": "^10.9.1",
    "tsc": "^2.0.4"
  }
}
```

</tr>
</tbody></table>



<table><tbody>
  <tr><td><strong>index.ts</strong></td></tr>
  <tr><td>
  
```ts
import pg from 'pg';
import { Connector, IpAddressTypes } from '@google-cloud/cloud-sql-connector';
const { Pool } = pg;

const connector = new Connector();
const clientOpts = await connector.getOptions({
  instanceConnectionName: (process.env.NODE_ENV === 'prod'
    ? process.env.DB_HOST_PROD
    : process.env.DB_HOST_DEV) as string,
  ipType: IpAddressTypes.PUBLIC,
});

const dbConfig = {
  database: process.env.DB_NAME,
  user: process.env.DB_USER,
  password:
    process.env.NODE_ENV === 'prod'
      ? process.env.DB_PASS_PROD
      : process.env.DB_PASS_DEV,
  ...clientOpts,
};

const pool = new Pool(dbConfig);
const {rows} = await pool.query('SELECT NOW()');
console.table(rows); // prints returned time value from server

await pool.end();
connector.close();
```

</tr>
</tbody></table>


<table><tbody>
  <tr><td><strong>tsconfig.json</strong></td></tr>
  <tr><td>
  
```json
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "compileOnSave": true,
  "include": ["src"]
}

```

</tr>
</tbody></table>

@Zwiqler94 do let us know in case it does not work for you but for now I'm going to close this issue since everything seems to be working as expected in the connector library.

Thank you for following up and I wish you all the best in your project 😊 

Last but not least, thanks a ton for debugging this and proposing solutions @edosrecki ❤️ Your help is appreciated!

**Closed by ruyadorno** 2023-09-21 18:59 UTC
Labels: priority: p1, type: question

**Comment by Zwiqler94** [comment] 2023-09-22 02:57
> I can confirm that the suggestions from @edosrecki works as expected, I ended up with a slightly tweaked, here is how it looks like in the end:
> 
> **package.json**
> ```json
> {
>   "name": "test-connector-express",
>   "version": "1.0.0",
>   "main": "index.js",
>   "type": "module",
>   "dependencies": {
>     "@google-cloud/cloud-sql-connector": "^0.5.1",
>     "@types/pg": "^8.10.2",
>     "pg": "^8.11.3",
>     "ts-node": "^10.9.1",
>     "tsc": "^2.0.4"
>   }
> }
> ```
> 
> **index.ts**
> ```ts
> import pg from 'pg';
> import { Connector, IpAddressTypes } from '@google-cloud/cloud-sql-connector';
> const { Pool } = pg;
> 
> const connector = new Connector();
> const clientOpts = await connector.getOptions({
>   instanceConnectionName: (process.env.NODE_ENV === 'prod'
>     ? process.env.DB_HOST_PROD
>     : process.env.DB_HOST_DEV) as string,
>   ipType: IpAddressTypes.PUBLIC,
> });
> 
> const dbConfig = {
>   database: process.env.DB_NAME,
>   user: process.env.DB_USER,
>   password:
>     process.env.NODE_ENV === 'prod'
>       ? process.env.DB_PASS_PROD
>       : process.env.DB_PASS_DEV,
>   ...clientOpts,
> };
> 
> const pool = new Pool(dbConfig);
> const {rows} = await pool.query('SELECT NOW()');
> console.table(rows); // prints returned time value from server
> 
> await pool.end();
> connector.close();
> ```
> 
> **tsconfig.json**
> ```json
> {
>   "compilerOptions": {
>     "module": "esnext",
>     "moduleResolution": "node",
>     "noImplicitReturns": true,
>     "noUnusedLocals": true,
>     "outDir": "lib",
>     "sourceMap": true,
>     "strict": true,
>     "target": "es2017",
>     "resolveJsonModule": true,
>     "esModuleInterop": true
>   },
>   "compileOnSave": true,
>   "include": ["src"]
> }
> ```
> 
> @Zwiqler94 do let us know in case it does not work for you but for now I'm going to close this issue since everything seems to be working as expected in the connector library.
> 
> Thank you for following up and I wish you all the best in your project 😊
> 
> Last but not least, thanks a ton for debugging this and proposing solutions @edosrecki ❤️ Your help is appreciated!

I'm still having issues, but I'll open a new issue but I believe this is a separate issue.
